language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24

env:
  global:
    - GRADLE_OPTS="-Xms128m"

branches:
  except:
    - gh-pages

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

script: ./gradlew build test