language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository

  licenses: 
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
  global:
    - GRADLE_OPTS="-Xms128m"

branches:
  except:
    - gh-pages

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle