language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository
  licenses: 
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
  global:
    - GRADLE_OPTS="-Xms128m"

jdk:
  - oraclejdk8

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.m2

script:
   - ./gradlew clean build